server:
  port: 18081

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: my_db
  drop-first: false
  enabled: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.11.12.51:3306/my_db?useUnicode=true&useSSL=false&amp;characterEncoding=utf8
    username: dev
    password: zfmm
    hikari:
      connection-timeout: 60000
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 50